[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
aptPkgs = ["chromium-browser", "chromium-chromedriver"]
